### ISSUE TITLE
Black screen and freezes

### ISSUE THREAD

**Issue by ONElua** [GrapheneCt/CapUnlocker#3]
There is an issue in v1.3
After closing adrenaline or any custom ABM bubble and trying to use Onemenu or Vitashell, or Retroarch the vita goes to a black screen and freezes, only way to turn it off is by holding power button to force the reebot.
PD: In v1.2 everything works fine

CFW 3.65 Enso
Add my config.txt
[config.txt](https://github.com/GrapheneCt/CapUnlocker/files/7290407/config.txt)

**Comment by Zarke669** [comment]
happens to me too.

**Comment by AndreDK7** [comment]
Same for me. Everytime i open Adrenaline or custom bubbles and then close i can't open anything on my Vita. I can't even turn off. I need to press my power button for some seconds to force my Vita to shutdown. Downgrade to 1.2 solved my problem.

**Comment by VMHoss** [comment]
I'm using Enso_ex 3.65, with the latest CapUnlocker. I have this issue as well.

**Comment by GrapheneCt** [comment]
The issue is related to thread capability limitations. For now using 1.2  is recommended solution, this will be fixed asap.

**Comment by GrapheneCt** [comment]
Fixed in v1.4
