### ISSUE TITLE
Vita wakes up at night 

### ISSUE THREAD

**Issue by flumpyflarb** [GrapheneCt/CapUnlocker#4]
Not sure it is has something in common with the other issue introduced in 1.3, so better I will write about it.
When using the latest release my OLED Vita wakes up at night and doesn't return to sleep - the result is a strongly depleted battery in the morning. Also, I can't reboot it normally (it just won't turn off) - I need to hold the power button for a long time.
On 1.2 version I observed no such behavior.
I'm on 3.65 Enso CFW.

**Comment by GrapheneCt** [comment]
Fixed in v1.4
